site_name: VacantPlanet Theme
dev_addr: localhost:7371
extra:
    project: VacantPlanet
copyright: © 2022-2024 ebene fünf GmbH
theme:
    name: vacantplanet
repo_url: https://github.com/vacantplanet/mkdocs-theme
markdown_extensions:
    - admonition
    - pymdownx.snippets:
        base_path: ["docs/code"]
